spring:
  application:
    name: api_gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8091/realms/het-security-realm

server:
  port: 9000

# Actuator & Prometheus
management:
  health:
    circuitbreakers:
      enabled: true
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "health,info,metrics,circuitbreakers,prometheus"
  metrics:
    tags:
      application: ${spring.application.name}

# Resilience4j Properties
resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 8
        failureRateThreshold: 20
        minimum-number-of-calls: 4
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 2
        automaticTransitionFromOpenToHalfOpenEnabled: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: Auth & User Service
        url: /docs/ms-auth/v3/api-docs
      - name: Product Service
        url: /docs/ms-product/v3/api-docs
      - name: Order Service
        url: /docs/ms-order/v3/api-docs
      - name: Stock Service
        url: /docs/ms-stock/v3/api-docs
  api-docs:
    path: /v3/api-docs
